### ISSUE TITLE
User Story A: List of upcoming events

### ISSUE THREAD

**Issue by ParedesGab** [ParedesGab/5-planning-demo-project#1]
**User story**
As a local resident, I want to see a list of upcoming community events, so that I can find interesting events to attend

**Acceptance Criteria**

- [ ] 1. The homepage displays a list of upcoming community events.
- [ ] 2. Each event listing includes the event name, date, time, and a brief description.
- [ ] 3. The list is responsive and looks good on all main device sizes.

**Tasks**

- [ ] 1. Add an HTML section on the homepage dedicated to upcoming community events.
- [ ] 2. Style the event list using Bootstrap.
- [ ] 3. Add some sample events including event name, date, time and brief description.
